// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmCqLnn84wwbneCeEXARy2TfrKKUpvXw4',
    appId: '1:395401802686:web:06894ac35dd83835d73fef',
    messagingSenderId: '395401802686',
    projectId: 'jarnama-app-6f69d',
    authDomain: 'jarnama-app-6f69d.firebaseapp.com',
    storageBucket: 'jarnama-app-6f69d.appspot.com',
    measurementId: 'G-2CJEFHMDBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGvgPn5FWq7UOcCQ9K2SOPi2KSr3Alq-8',
    appId: '1:395401802686:android:c1a9f7c18ecf2a55d73fef',
    messagingSenderId: '395401802686',
    projectId: 'jarnama-app-6f69d',
    storageBucket: 'jarnama-app-6f69d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSf3p-H0ePLg0Z4CpTnyv4xGjZ6kifEs',
    appId: '1:395401802686:ios:d50cb79c56e6489ad73fef',
    messagingSenderId: '395401802686',
    projectId: 'jarnama-app-6f69d',
    storageBucket: 'jarnama-app-6f69d.appspot.com',
    iosClientId: '395401802686-12sdpgt558c4tb9lsfdp4cncoqdbhe0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSf3p-H0ePLg0Z4CpTnyv4xGjZ6kifEs',
    appId: '1:395401802686:ios:d50cb79c56e6489ad73fef',
    messagingSenderId: '395401802686',
    projectId: 'jarnama-app-6f69d',
    storageBucket: 'jarnama-app-6f69d.appspot.com',
    iosClientId: '395401802686-12sdpgt558c4tb9lsfdp4cncoqdbhe0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
